version: "3.8"

services:
  webapp:
    build: .
    ports:
      - "8501:8501" # Map port 8501
    volumes:
      - .:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: always

  api:
    container_name: churn-api
    build: .
    ports:
      - "8000:8000" # Map port 8000
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
